import type { EggMeta } from './types';
import { createBaseEgg } from '../eggs/base';

const baseEgg = (version: string, nickname: string, accent: string) => async () => ({
  default: createBaseEgg({ version, nickname, accent }),
});

/**
 * Every egg in ascending Android API order.
 *
 * `load` is only present once an egg is actually implemented; the shell renders
 * the rest as disabled "planned" entries so the roadmap stays visible.
 */
export const EGGS: readonly EggMeta[] = [
  {
    id: 'base',
    api: 1,
    version: '1.0',
    codename: 'Base',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('1.0', 'Base', '#9E9E9E'),
  },
  {
    id: 'petit-four',
    api: 2,
    version: '1.1',
    codename: 'Petit Four',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('1.1', 'Petit Four', '#B39DDB'),
  },
  {
    id: 'cupcake',
    api: 3,
    version: '1.5',
    codename: 'Cupcake',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('1.5', 'Cupcake', '#F48FB1'),
  },
  {
    id: 'donut',
    api: 4,
    version: '1.6',
    codename: 'Donut',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('1.6', 'Donut', '#FFCC80'),
  },
  {
    id: 'eclair',
    api: 5,
    version: '2.0 – 2.1',
    codename: 'Eclair',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('2.0', 'Eclair', '#90CAF9'),
  },
  {
    id: 'froyo',
    api: 8,
    version: '2.2',
    codename: 'Froyo',
    title: 'PlatLogo',
    status: 'ready',
    load: baseEgg('2.2', 'Froyo', '#A5D6A7'),
  },
  {
    id: 'gingerbread',
    api: 9,
    version: '2.3',
    codename: 'Gingerbread',
    title: 'Zombie Art',
    status: 'ready',
    load: () => import('../eggs/gingerbread'),
  },
  {
    id: 'honeycomb',
    api: 11,
    version: '3.0 – 3.2',
    codename: 'Honeycomb',
    title: 'REZZZZZZZ',
    status: 'ready',
    load: () => import('../eggs/honeycomb'),
  },
  {
    id: 'ice-cream-sandwich',
    api: 14,
    version: '4.0',
    codename: 'Ice Cream Sandwich',
    title: 'Nyandroid',
    status: 'ready',
    load: () => import('../eggs/icecreamsandwich'),
  },
  {
    id: 'jelly-bean',
    api: 16,
    version: '4.1 – 4.3',
    codename: 'Jelly Bean',
    title: 'BeanBag',
    status: 'ready',
    load: () => import('../eggs/jellybean'),
  },
  {
    id: 'kitkat',
    api: 19,
    version: '4.4',
    codename: 'KitKat',
    title: 'Dessert Case',
    status: 'ready',
    load: () => import('../eggs/kitkat'),
  },
  {
    id: 'webdriver-torso',
    api: 20,
    version: 'L Preview',
    codename: 'L Preview',
    title: 'Webdriver Torso',
    status: 'ready',
    load: () => import('../eggs/webdrivertorso'),
  },
  {
    id: 'lollipop',
    api: 21,
    version: '5.0 – 5.1',
    codename: 'Lollipop',
    title: 'LLand',
    status: 'ready',
    load: () => import('../eggs/lollipop'),
  },
  {
    id: 'marshmallow',
    api: 23,
    version: '6.0',
    codename: 'Marshmallow',
    title: 'MLand',
    status: 'ready',
    load: () => import('../eggs/marshmallow'),
  },
  {
    id: 'nougat',
    api: 24,
    version: '7.0 – 7.1',
    codename: 'Nougat',
    title: 'Neko',
    status: 'ready',
    load: () => import('../eggs/nougat'),
  },
  {
    id: 'oreo',
    api: 26,
    version: '8.0 – 8.1',
    codename: 'Oreo',
    title: 'Ocquarium',
    status: 'ready',
    load: () => import('../eggs/oreo'),
  },
  {
    id: 'pie',
    api: 28,
    version: '9.0',
    codename: 'Pie',
    title: 'PAINT.APK',
    status: 'ready',
    load: () => import('../eggs/pie'),
  },
  {
    id: 'q',
    api: 29,
    version: '10',
    codename: 'Quince Tart',
    title: 'Icon Quiz',
    status: 'ready',
    load: () => import('../eggs/q'),
  },
  {
    id: 'r',
    api: 30,
    version: '11',
    codename: 'Red Velvet Cake',
    title: 'Cat Controls',
    status: 'ready',
    load: () => import('../eggs/r'),
  },
  {
    id: 's',
    api: 31,
    version: '12 – 12L',
    codename: 'Snow Cone',
    title: 'Paint Chips',
    status: 'ready',
    load: () => import('../eggs/s'),
  },
  {
    id: 'tiramisu',
    api: 33,
    version: '13',
    codename: 'Tiramisu',
    title: 'Paint Chips',
    status: 'ready',
    load: () => import('../eggs/tiramisu'),
  },
  {
    id: 'upside-down-cake',
    api: 34,
    version: '14',
    codename: 'Upside Down Cake',
    title: 'Landroid',
    status: 'ready',
    load: () => import('../eggs/upsidedowncake'),
  },
  {
    id: 'vanilla-ice-cream',
    api: 35,
    version: '15',
    codename: 'Vanilla Ice Cream',
    title: 'Landroid',
    status: 'ready',
    load: () => import('../eggs/vanillaicecream'),
  },
  {
    id: 'baklava',
    api: 36,
    version: '16',
    codename: 'Baklava',
    title: 'Landroid',
    status: 'ready',
    load: () => import('../eggs/baklava'),
  },
  {
    id: 'cinnamon-bun',
    api: 37,
    version: '17',
    codename: 'Cinnamon Bun',
    title: 'Heptadecagram + Landroid',
    status: 'ready',
    load: () => import('../eggs/cinnamonbun'),
  },
  {
    id: 'android-next',
    api: 10000,
    version: 'Next',
    codename: 'Android Next',
    title: 'Release Timeline',
    status: 'ready',
    load: () => import('../eggs/androidnext'),
  },
  {
    id: 'rocket-launcher',
    api: 10001,
    version: '2.x',
    codename: 'RocketLauncher',
    title: 'launcher2 Home',
    status: 'ready',
    load: () => import('../eggs/rocketlauncher'),
  },
];

export function findEgg(id: string): EggMeta | undefined {
  return EGGS.find((egg) => egg.id === id);
}

export function isReady(meta: EggMeta): boolean {
  return meta.status === 'ready' && meta.load !== undefined;
}
